// react/react17-recoil/src/Child.tsx
import React, { FunctionComponent } from "react";
import { atom, useRecoilState } from "recoil";

export const countState = atom({
  key: "count",
  default: 0,
});

export type Props = Record<string, unknown>;

const Child: FunctionComponent<Props> = (props: Props, ref) => {
  const [count, setCount] = useRecoilState(countState);

  return (
    <div>
      <h3>Child</h3>
      <p>Count: {count}</p>
      <button onClick={() => setCount(count + 1)}>increase</button>
    </div>
  );
};

export default Child;

// vue/vue2-basic-directive-v-on：hook/src/Child.vue
<template>
  <div>
    <h2>Child Component</h2>
    <p>count : {{ count }}</p>
    <button @click="count++">increase count</button>
  </div>
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  data() {
    return {
      count: 1,
    };
  },
});
</script>

<style></style>
