// react/react17-basic-useRef/src/Child.tsx
import React, { FunctionComponent } from "react";

export type Props = Record<string, unknown>;

const Child: FunctionComponent<Props> = (props: Props, ref) => {
  return (
    <div>
      <h3>Child</h3>
      <div ref={ref}></div>
      <button
        onClick={() => {
          console.log("[Child] child div ref created by App Component", ref);
        }}
      >
        child button
      </button>
    </div>
  );
};

export default Child;

// svelte/svelte3-basic-tutorial-lifecycle-{afterUpdate,beforeUpdate}/src/Child.svelte
<script lang="ts">
  import { afterUpdate, beforeUpdate } from "svelte";

  let childNum = 0;
  export let propNum;

  afterUpdate(() => {
    console.log("[Child] afterUpdate");
  });

  beforeUpdate(() => {
    console.log("[Child] beforeUpdate");
  });
</script>

<div>
  <h2>Child</h2>
  <button on:click={() => childNum++}>increase childNum</button>
  <button on:click={() => propNum++}>increase propNum</button>
  <p>childNum: {childNum}</p>
  <p>propNum : {propNum}</p>
</div>

<style>
</style>
