// nuxt/nuxt2.15-basic-config-target/pages/users.vue
<template>
  <div>
    <h1>Users</h1>
    <p>{{ users }}</p>
  </div>
</template>

<script lang="ts">
import { NuxtAppOptions } from "@nuxt/types";

export default {
  data: () => ({
    users: null,
  }),
  async fetch() {
    // does not called after nuxt generate
    const url = `https://jsonplaceholder.typicode.com/users`;
    const response = await fetch(url);

    this.users = await response.json();
  },
} as NuxtAppOptions;
</script>

<style scoped></style>

// svelteKit/svelteKit1-basic-hooks-handle-function/src/routes/users.svelte
<script context="module" lang="ts">
  import type { Load } from "@sveltejs/kit";

  type JSONValue =
    | string
    | number
    | boolean
    | null
    | JSONValue[]
    | { [key: string]: JSONValue };

  export const load: Load = async ({ fetch }) => {
    const response = await fetch(`https://jsonplaceholder.typicode.com/users`);

    return {
      props: {
        users: (await response.json()) as JSONValue,
      },
    };
  };
</script>

<script lang="ts">
  export let users;
</script>

<h1>Users</h1>
<p>{JSON.stringify(users)}</p>

<style>
</style>
